function out1 = TiltrotorModel_Eul_Perturbed(in1,in2)
%TILTROTORMODEL_EUL_PERTURBED
%    OUT1 = TILTROTORMODEL_EUL_PERTURBED(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-May-2020 10:55:12

a1 = in2(5,:);
a2 = in2(6,:);
a3 = in2(7,:);
a4 = in2(8,:);
p = in1(10,:);
phi = in1(4,:);
psi = in1(6,:);
q = in1(11,:);
r = in1(12,:);
theta = in1(5,:);
u1 = in2(1,:);
u2 = in2(2,:);
u3 = in2(3,:);
u4 = in2(4,:);
xdot = in1(7,:);
ydot = in1(8,:);
zdot = in1(9,:);
t2 = cos(a1);
t3 = cos(a2);
t4 = cos(a3);
t5 = cos(a4);
t6 = cos(phi);
t7 = cos(psi);
t8 = sin(a1);
t9 = sin(a2);
t10 = sin(a3);
t11 = sin(a4);
t12 = cos(theta);
t13 = sin(phi);
t14 = sin(psi);
t15 = sin(theta);
t16 = tan(theta);
t17 = u1.^2;
t18 = u2.^2;
t19 = u3.^2;
t20 = u4.^2;
t21 = t8.*t17;
t22 = t9.*t18;
t23 = t10.*t19;
t24 = t11.*t20;
t25 = t2.*t17;
t26 = t3.*t18;
t27 = t4.*t19;
t28 = t5.*t20;
t29 = -t23;
t30 = -t24;
t33 = t25+t26+t27+t28;
t31 = t21+t29;
t32 = t22+t30;
out1 = [xdot;ydot;zdot;p+q.*t13.*t16+r.*t6.*t16;q.*t6-r.*t13;(q.*t13+r.*t6)./t12;t31.*(t6.*t14-t7.*t13.*t15).*(-1.35e-5)+t33.*(t13.*t14+t6.*t7.*t15).*1.35e-5-t7.*t12.*t32.*1.35e-5;t31.*(t6.*t7+t13.*t14.*t15).*1.35e-5-t33.*(t7.*t13-t6.*t14.*t15).*1.35e-5-t12.*t14.*t32.*1.35e-5;t15.*t32.*1.35e-5+t6.*t12.*t33.*1.35e-5+t12.*t13.*t31.*1.35e-5-9.81e+2./1.0e+2;t22.*(-3.36e-6)+t24.*3.36e-6+t26.*3.564e-5-t28.*3.564e-5-q.*r.*(1.9e+1./2.5e+1);t21.*3.36e-6-t23.*3.36e-6-t25.*3.564e-5+t27.*3.564e-5+p.*r.*(1.9e+1./2.5e+1);t21.*2.025e-5+t22.*2.025e-5+t23.*2.025e-5+t24.*2.025e-5+t25.*1.909090909090909e-6-t26.*1.909090909090909e-6+t27.*1.909090909090909e-6-t28.*1.909090909090909e-6];
